### ISSUE TITLE
UR10 description yields a DaeBrokenRefError

### ISSUE THREAD

**Issue by stephane-caron** [petrikvladimir/RoboMeshCat#9]
The UR10 description from example-robot-data ([this one](https://github.com/Gepetto/example-robot-data/blob/master/robots/ur_description/urdf/ur10_robot.urdf)) yields a Dae BrokenRefError with RoboMeshCat:

```
collada.common.DaeBrokenRefError: DaeBrokenRefError: Light #Lamp-light not found in library
```

It loads successfully with Pinocchio:

![image](https://user-images.githubusercontent.com/1189580/204534322-1127fb64-132b-4127-960d-f2500f6831f5.png)

**Comment by petrikvladimir** [comment]
Thanks. Seems to be an error in the example-robot-data dae files introduced here: 
https://github.com/Gepetto/example-robot-data/commit/ed85b8720b0a43d3978537991f3aa8dae1a3787d
The library for light was removed, but the references to light instances remained. I will create a PR to example-robot-data to fix it.

**Comment by stephane-caron** [comment]
OK, sounds good.

There are other descriptions that may have similar errors in the wild. For instance the same issue happens on this [fetch_description](https://github.com/openai/roboschool/tree/master/roboschool/models_robot/fetch_description) (for a camera not found). Pinocchio or [yourdfpy](https://github.com/clemense/yourdfpy/) (which also depends on ``trimesh``) just ignore those issues.

**Comment by petrikvladimir** [comment]
Thanks for pointing me to yourdfpy solution. I implemented their workaround (i.e., trimesh.load(..., ignore_broken=True) that allows loading broken UR robots from example-robot-data.
